# Build Stage
FROM python:3.11-slim-bookworm AS builder

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml ./
COPY packages/shared-python/ ./packages/shared-python/
COPY apps/agent/ ./apps/agent/

RUN uv venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN uv pip install -e ./packages/shared-python -e ./apps/agent

# Runner Stage
FROM python:3.11-slim-bookworm AS runner

WORKDIR /app

COPY --from=builder /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY apps/agent/agent /app/agent
COPY apps/agent/main.py /app/main.py

CMD ["python", "main.py"]
